#- name: Install nginx
#  ansible.builtin.yum:
#     name: httpd
#     state: latest
#- name: Start Nginx
#  ansible.builtin.systemd:
#    name: nginx
#    state: started
#    enabled: yes

- name: private variable
  ansible.builtin.debug:
    msg: URL = {{ url }}

- name: private variable - task variable defined
  ansible.builtin.debug:
    msg: URL = {{ url }}
  vars:
     url: task.google.com
