- name: Demo on conditions
  host: all
  Connection: local
  var:
    fruit: true
    vegetable: false

  tasks:
    - name: Print fruit Name
      ansible.builtin.debug:
        msg: Fruit Name - Apple
      when: fruit is true

    - name: print Vegetable Name
      ansible.builtin.debug:
          msg: Vegetable Name - Carrot
      when: vegetable is true
